# Generated by Django 5.2.17 on 2026-10-05 17:42

import datetime
import django.contrib.postgres.operations
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.lookups
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('court_type', models.CharField(choices=[('indoor', 'Крытый'), ('outdoor', 'Открытый')], max_length=7)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('surface_status', models.CharField(choices=[('available', 'Доступен'), ('drying', 'Просушка'), ('maintenance', 'Обслуживание')], default='available', max_length=11)),
                ('last_inspected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='court_name_not_blank'), models.CheckConstraint(condition=models.Q(('court_type__in', ['indoor', 'outdoor'])), name='court_type_valid'), models.CheckConstraint(condition=models.Q(('surface_status__in', ['available', 'drying', 'maintenance'])), name='court_surface_status_valid'), models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='court_latitude_valid'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='court_longitude_valid')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='customer_name_not_blank'), models.CheckConstraint(condition=models.Q(('phone__regex', '\\S')), name='customer_phone_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Действующая'), ('cancelled', 'Отменена')], default='active', max_length=9)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.court')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('created', 'Создание'), ('rescheduled', 'Перенос'), ('cancelled', 'Отмена'), ('archived', 'Архивация')], max_length=11)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField()),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_events', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='bookings.booking')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type__in', ['created', 'rescheduled', 'cancelled', 'archived'])), name='booking_event_type_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'cancelled'])), name='booking_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('archived_at__isnull', True), ('status', 'cancelled'), _connector='OR'), name='booking_archive_only_cancelled'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='booking_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gte', django.db.models.expressions.CombinedExpression(models.F('starts_at'), '+', models.Value(datetime.timedelta(seconds=3600))))), name='booking_minimum_one_hour'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(models.F('starts_at'), models.Func(models.Value(datetime.timedelta(seconds=600)), models.F('starts_at'), models.Value(datetime.datetime(2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)), function='DATE_BIN', output_field=models.DateTimeField())), name='booking_starts_at_ten_minutes'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(models.F('ends_at'), models.Func(models.Value(datetime.timedelta(seconds=600)), models.F('ends_at'), models.Value(datetime.datetime(2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)), function='DATE_BIN', output_field=models.DateTimeField())), name='booking_ends_at_ten_minutes'),
        ),
    ]
